ru:
  main_sites:
    phones:
      title: 'Телефонный справочник'
      link: 'https://directory.tusur.ru'

    edu:
      title: 'Научно-образовательный портал'
      link: 'https://edu.tusur.ru'

    timetable:
      title: 'Расписание занятий'
      link: 'https://timetable.tusur.ru'

    attendance:
      title: 'Журнал посещаемости'
      link: 'https://attendance.tusur.ru'

    radioelektronik:
      title: 'Газета &laquo;Радиоэлектроник&raquo;'
      link: 'http://re.tusur.ru'

  additional_sites:
    abiturients:
      title: 'Абитуриентам'
      link: 'http://abiturient.tusur.ru/'

    students:
      title: 'Студентам'
      link: 'https://tusur.ru/ru/studentam'

    magistrants:
      title: 'Магистрантам'
      link: 'https://magistrant.tusur.ru'

    postgraduates:
      title: 'Аспирантам'
      link: 'https://tusur.ru/ru/aspirantam'

    staff:
      title: 'Сотрудникам'
      link: 'https://tusur.ru/ru/sotrudnikam'

en:
  main_sites:
    phones:
      title: 'Phonebook'
      link: 'https://directory.tusur.ru'

    edu:
      title: 'Research and Education Portal'
      link: 'https://edu.tusur.ru'

    timetable:
      title: 'Timetable of classes'
      link: 'https://timetable.tusur.ru'

    attendance:
      title: 'Attendance History'
      link: 'https://attendance.tusur.ru'

    radioelektronik:
      title: 'Newspaper &laquo;RADIOELECTRONICS&raquo;'
      link: 'http://re.tusur.ru'

  additional_sites:
    admission:
      title: 'Admission'
      link: 'https://tusur.ru/en/admission'

    degree-programs:
      title: 'Degree Programs'
      link: 'https://tusur.ru/en/degree-programs/bachelor-programs'

    employment:
      title: 'Employment'
      link: 'https://tusur.ru/en/employment'

    publications:
      title: 'Publications'
      link: 'https://tusur.ru/en/publications'
